#!/bin/sh
# Copyright (c) 2009-2010 Apple Inc. All rights reserved.

cp -X ${SHARED_DERIVED_FILE_DIR}/*.cat ${CODESIGNING_FOLDER_PATH}/Resources/Catalogs/

rm ${CODESIGNING_FOLDER_PATH}/Resources/Catalogs/junk.c
