#! /bin/bash
#
# Copyright (c) 2010 Apple Inc. All rights reserved.
#
# @APPLE_LICENSE_HEADER_START@
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1.  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# 2.  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 3.  Neither the name of Apple Inc. ("Apple") nor the names of its
#     contributors may be used to endorse or promote products derived from
#     this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY APPLE AND ITS CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL APPLE OR ITS CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Portions of this software have been released under the following terms:
#
# (c) Copyright 1991 OPEN SOFTWARE FOUNDATION, INC.
# (c) Copyright 1991 HEWLETT-PACKARD COMPANY
# (c) Copyright 1991 DIGITAL EQUIPMENT CORPORATION
# Portions Copyright (c) 2010 Apple Inc.
# To anyone who acknowledges that this file is provided "AS IS"
# without any express or implied warranty:
# permission to use, copy, modify, and distribute this file for any
# purpose is hereby granted without fee, provided that the above
# copyright notices and this notice appears in all source code copies,
# and that none of the names of Open Software Foundation, Inc., Hewlett-
# Packard Company, Apple Inc. or Digital Equipment Corporation be used
# in advertising or publicity pertaining to distribution of the software
# without specific, written prior permission.  Neither Open Software
# Foundation, Inc., Hewlett-Packard Company, Apple Inc. nor Digital
# Equipment Corporation makes any representations about the suitability
# of this software for any purpose.
#
#
# @APPLE_LICENSE_HEADER_END@
#

set -e

# Turn foo.[ly] into foo.h
outfile_name()
{
    local input=$(basename "$1")
    local extension="$2"
    echo ${input%.[ly]}.${extension}
}

# Turn fool.y into fooyy
parser_prefix()
{
    local input=$(basename "$1")
    echo ${input%[ly].[ly]}yy
}

run()
{
    local status

    echo "$@"
    xcrun "$@"
}

OUTDIR="$(dirname ${SCRIPT_OUTPUT_FILE_0})"

LEXER="$(basename ${SCRIPT_INPUT_FILE_0})"
PARSER="$(basename ${SCRIPT_INPUT_FILE_1})"
PREFIX="$(parser_prefix ${PARSER})"

mkdir -p "$OUTDIR"
cd "$OUTDIR"

run flex -P${PREFIX} -o $(outfile_name ${LEXER} c) ${SCRIPT_INPUT_FILE_0}
run bison -v -d -p ${PREFIX} -o $(outfile_name ${PARSER} c) ${SCRIPT_INPUT_FILE_1}

echo $LEXER \-\> $(outfile_name ${LEXER} c) $(outfile_name ${LEXER} h)
echo $PARSER \-\> $(outfile_name ${PARSER} c) $(outfile_name ${PARSER} h)
