#! /bin/sh
# Copyright (c) 2010 Apple Inc. All rights reserved.

# This script works around the rather inflexible Xcode Copy Headers
# phase by removing the extra files it copies. for the base DCE
# headers, we use a folder reference in Copy Headers, but that causes
# Xcode to copy *everything* in that directory. We have to remove the
# unwanted items afterwards.

# Typical values of CONFIGURATION_BUILD_DIR and CONTENTS_FOLDER_PATH:
#     setenv CONFIGURATION_BUILD_DIR /Volumes/Scratch/dcerpc.git/build/Debug
#     setenv CONTENTS_FOLDER_PATH DCERPC.framework/Versions/A

find ${CONFIGURATION_BUILD_DIR}/${CONTENTS_FOLDER_PATH} -name \*.c -print0 | \
	 xargs -0 rm
