#!/bin/sh
if test ! -e "${SRCROOT}/dcerpc/configure"; then
    cd "${SRCROOT}/dcerpc"
    echo "Running buildconf and configure"
    ./buildconf
    ./configure --disable-dependency-tracking --enable-idldumpers
else
    echo "buildconf and configure have already been executed"
fi
