#!/bin/sh
if test ! -e "${SRCROOT}/configure"; then
    cd "${SRCROOT}"
    echo "Running buildconf and configure"
    ./buildconf
    ./configure
else
    echo "buildconf and configure have already been executed"
fi
