name: Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y flex bison autoconf automake libtool
    - name: configure
      run: |
        cd dcerpc
        ./bootstrap
        ./configure
    - name: make
      run: make -C dcerpc -j4
    - name: make check
      run: make -C dcerpc check
      timeout-minutes: 5
    - name: make distcheck
      run: make -C dcerpc distcheck
